---
title: "h2o-insurance"
author: "Leon Yuan"
format: pdf
editor: visual
---

```{r}
#| output: false
library(tidyverse)
```

```{r}
versions::installed.versions("h2o")
```

```{r}
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }
```

```{r}
pkgs <- c("RCurl","jsonlite")
for (pkg in pkgs) {
  if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}
```

```{r}
install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R")))
```

```{r}
library(h2o)
h2o.init()
#demo(h2o.kmeans)
```

```{r}
# Import a sample binary outcome train/test set into H2O
train <- h2o.importFile("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
test <- h2o.importFile("https://s3.amazonaws.com/erin-data/higgs/higgs_test_5k.csv")

# Identify predictors and response
y <- "response"
x <- setdiff(names(train), y)

# For binary classification, response should be a factor
train[, y] <- as.factor(train[, y])
test[, y] <- as.factor(test[, y])

# Run AutoML for 20 base models
aml <- h2o.automl(x = x, y = y,
                  training_frame = train,
                  max_models = 20,
                  seed = 1)

# View the AutoML Leaderboard
lb <- aml@leaderboard
print(lb, n = nrow(lb))  # Print all rows instead of default (6 rows)
```

```{r}
# Import a sample binary outcome train/test set into H2O
train <- h2o.importFile("/Users/liyuan/Documents/SMU/Fall\ 2022/6324/final/insurance/data/train_adjusted.csv")
valid <- h2o.importFile("/Users/liyuan/Documents/SMU/Fall\ 2022/6324/final/insurance/data/valid_adjusted.csv")
test <- h2o.importFile("/Users/liyuan/Documents/SMU/Fall\ 2022/6324/final/insurance/data/test_adjusted.csv")

h2o.describe(train)

# Identify predictors and response
y <- "charges"
x <- setdiff(names(train), y)

# For binary classification, response should be a factor
char <- c('sex', 'smoker', 'region', 'children')
for(i in char){
  train[, i] <- as.factor(train[, i])
  valid[, i] <- as.factor(valid[, i])
  test[, i] <- as.factor(test[, i])
}

# Run AutoML for 20 base models
aml <- h2o.automl(x = x, y = y,
                  training_frame = train,
                  validation_frame = valid,
                  leaderboard_frame = test,
                  max_models = 30,
                  project_name = "insurance_autoML",
                  seed = 2)

# View the AutoML Leaderboard
lb <- aml@leaderboard
print(lb, n = nrow(lb))  # Print all rows instead of default (6 rows)
View(as.data.frame(lb))
```

```{r}
pred <- h2o.predict(aml, test)
as.data.frame(pred)
```

```{r}
# Get leaderboard with all possible columns
lb <- h2o.get_leaderboard(object = aml, extra_columns = "ALL")
lb
```

```{r}
# this is equivalent to
m <- h2o.get_best_model(aml)
m
```


```{r}
# Explain an AutoML object
exa <- h2o.explain(aml, test)
exa
```

```{r}
learning_curve_plot <- h2o.learning_curve_plot(aml@leader)
learning_curve_plot
```

